apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: nonoel/discovery-service:latest  # Remplacez par l'image Docker du Docker Hub
          ports:
            - containerPort: 8761  # Port pour le service Discovery (Eureka)

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-service  # Le label doit correspondre à celui du Deployment
  ports:
    - protocol: TCP
      port: 8761           # Port exposé sur le service
      targetPort: 8761     # Port sur lequel le conteneur écoute
  type: ClusterIP          # Accès interne dans le cluster uniquement
