apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: default  # Remplacez "default" par votre namespace si différent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: nonoel/discovery-service:latest
          ports:
            - containerPort: 8761
          readinessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: default  # Remplacez "default" par votre namespace si différent
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
